/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetrosIndexRouteImport } from './routes/retros/index'
import { Route as RetrosNewRouteImport } from './routes/retros/new'
import { Route as RetrosRetroIdRouteImport } from './routes/retros/$retroId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosIndexRoute = RetrosIndexRouteImport.update({
  id: '/retros/',
  path: '/retros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosNewRoute = RetrosNewRouteImport.update({
  id: '/retros/new',
  path: '/retros/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosRetroIdRoute = RetrosRetroIdRouteImport.update({
  id: '/retros/$retroId',
  path: '/retros/$retroId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/retros/': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/retros': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/retros/': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/retros/$retroId'
    | '/retros/new'
    | '/retros/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/retros/$retroId'
    | '/retros/new'
    | '/retros'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/retros/$retroId'
    | '/retros/new'
    | '/retros/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  RetrosRetroIdRoute: typeof RetrosRetroIdRoute
  RetrosNewRoute: typeof RetrosNewRoute
  RetrosIndexRoute: typeof RetrosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/': {
      id: '/retros/'
      path: '/retros'
      fullPath: '/retros/'
      preLoaderRoute: typeof RetrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/new': {
      id: '/retros/new'
      path: '/retros/new'
      fullPath: '/retros/new'
      preLoaderRoute: typeof RetrosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/$retroId': {
      id: '/retros/$retroId'
      path: '/retros/$retroId'
      fullPath: '/retros/$retroId'
      preLoaderRoute: typeof RetrosRetroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  RetrosRetroIdRoute: RetrosRetroIdRoute,
  RetrosNewRoute: RetrosNewRoute,
  RetrosIndexRoute: RetrosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
