/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetrosIndexRouteImport } from './routes/retros/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as RetrosNewRouteImport } from './routes/retros/new'
import { Route as RetrosRetroIdRouteImport } from './routes/retros/$retroId'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations/$orgId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosIndexRoute = RetrosIndexRouteImport.update({
  id: '/retros/',
  path: '/retros/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosNewRoute = RetrosNewRouteImport.update({
  id: '/retros/new',
  path: '/retros/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrosRetroIdRoute = RetrosRetroIdRouteImport.update({
  id: '/retros/$retroId',
  path: '/retros/$retroId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/retros/': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/retros': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/retros/$retroId': typeof RetrosRetroIdRoute
  '/retros/new': typeof RetrosNewRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/retros/': typeof RetrosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/admin/users'
    | '/organizations/$orgId'
    | '/retros/$retroId'
    | '/retros/new'
    | '/teams/$teamId'
    | '/organizations/'
    | '/retros/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/admin/users'
    | '/organizations/$orgId'
    | '/retros/$retroId'
    | '/retros/new'
    | '/teams/$teamId'
    | '/organizations'
    | '/retros'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/team'
    | '/templates'
    | '/admin/users'
    | '/organizations/$orgId'
    | '/retros/$retroId'
    | '/retros/new'
    | '/teams/$teamId'
    | '/organizations/'
    | '/retros/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
  RetrosRetroIdRoute: typeof RetrosRetroIdRoute
  RetrosNewRoute: typeof RetrosNewRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  RetrosIndexRoute: typeof RetrosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/': {
      id: '/retros/'
      path: '/retros'
      fullPath: '/retros/'
      preLoaderRoute: typeof RetrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/new': {
      id: '/retros/new'
      path: '/retros/new'
      fullPath: '/retros/new'
      preLoaderRoute: typeof RetrosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retros/$retroId': {
      id: '/retros/$retroId'
      path: '/retros/$retroId'
      fullPath: '/retros/$retroId'
      preLoaderRoute: typeof RetrosRetroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
  RetrosRetroIdRoute: RetrosRetroIdRoute,
  RetrosNewRoute: RetrosNewRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  RetrosIndexRoute: RetrosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
